AUDIO_FILE: "examples/How-will-AI-change-the-world.mp3"
TRANSCRIPT_DIR: "transcripts"

WHISPER_MODEL: "base"
OPENAI_MODEL: "gpt-3.5-turbo-16k"

RESULTS_DIR: "results"

DREAMBOAT_BASE_URL: "https://dev.dreamboat.ai/v1/proxy"

USER_FILE: "person.txt"

FORCE_TRANSCRIPT: "0"

USE_WHISPER_API: "1"
